### ISSUE TITLE
Wiki: English Syntax Error near 'provides sth. to use'

### ISSUE THREAD

**Issue by Librazy** [lhmouse/mcfgthread#1]
The usage "provides sth. to use sth" is not a idiomatic expression and it is not grammatically correct. IMO ,it's better to use "provides sth. for sth". 
e.g. 
"This header provides APIs for mutexes." 
"This header provides APIs for operating thread local storage(TLS)."

**Comment by lhmouse** [comment]
Your 'Syntax Error' is a grammar error.

**Comment by Librazy** [comment]
I thinking me is intented for saying liked this

**Comment by lhmouse** [comment]
Fixed then, as well as a little more.
