### ISSUE TITLE
__gthread_key_delete() and destructors

### ISSUE THREAD

**Issue by lhmouse** [lhmouse/mcfgthread#11]
According to [this specification](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_key_delete.html) in POSIX 2013:

> The `pthread_key_delete()` function shall be callable from within destructor functions. No destructor functions shall be invoked by `pthread_key_delete()`. **Any destructor function that may have been associated with key shall no longer be called upon thread exit.**

This contradicts `__gthread_key_delete()` in  **mcfgthread** which preserves destructors deferred upon thread exit.

Neither [the C11 standard](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1570.pdf) nor the [GNU documentation of `__gthread_*` interfaces](https://gcc.gnu.org/viewcvs/gcc/trunk/libgcc/gthr.h?view=markup) says a word about such behavior. Personally I refuse to regard POSIX crap. Nonetheless, any further discussion is welcome.

**Comment by AntiMoron** [comment]
bmjl.

**Comment by lhmouse** [comment]
Closed as no discussion is incoming. Please reopen this issue sometime, if necessary.
