### ISSUE TITLE
Any speed test / performance comparation?

### ISSUE THREAD

**Issue by CarterLi** [lhmouse/mcfgthread#15]
For example creating 1K threads and joining them, PingPang test for 1M times, compare with winpthread implementation & VC++'s std::thread implementation ( although not very meaningful )

> 该项目使用了很多未有微软文档的系统调用来保证运行效率

You say P without data 😄

**Comment by lhmouse** [comment]
If you would like to write one, I am glad to help. :joy:

**Comment by FrankHB** [comment]
PingPang shenmegui.

**Comment by CarterLi** [comment]
Here's my buggy example
```c++
#include <cstdio>
#include <thread>
#include <condition_variable>
#include <mutex>
#include <chrono>

int main() {
    volatile int ping = 0, pang = 0;
    auto clock = std::chrono::high_resolution_clock::now();
    std::condition_variable cvPing, cvPang;

    std::thread thd([&](){
        std::mutex mtx;
        cvPing.notify_all();
        std::unique_lock<std::mutex> lock(mtx);
        while (pang < 1000) {
            cvPang.wait(lock);
            ++pang;
            std::printf("PANG: %d\n", pang);
            cvPing.notify_all();
        }
    });

    std::mutex mtx;
    std::unique_lock<std::mutex> lock(mtx);
    while (ping < 1000) {
        cvPing.wait(lock);
        ++ping;
        std::printf("PING: %d\n", ping);
        cvPang.notify_all();
    }

    thd.join();
    std::printf("\nPING: %d, PANG: %d, Time used: %lldms", ping, pang, (std::chrono::high_resolution_clock::now() - clock).count() / 1000000);
}
```
Sometimes it dead locks because one thread is trying to notify another thread before it sleeps...

**Comment by lhmouse** [comment]
> Deadlocks happen frequently because one thread is trying to awake another thread before it sleeps...

The two threads **must** share the same mutex.

**Comment by CarterLi** [comment]
> The two threads must share the same mutex.

How? Instead of waiting a cv, one thread is blocked outside the lock, while another thread which aquiring the lock is trying to notify it?
And why? They use different cv, so they can use different mutex.

**Comment by lhmouse** [comment]
> And why? They use different cv, so they can use different mutex.

The mutex is used to protect not only shared resources, but also the condition variable itself. Your condition variables are **unprotected** thus `wait()` and `notify_all()` can happen in any order, resulting in deadlocks.

**Comment by CarterLi** [comment]
> The mutex is used to protect not only shared resources, but also the condition variable itself. Your condition variables are unprotected thus wait() and notify_all() can happen in any order, resulting in deadlocks.

Well, that makes sence. I fixed my code. Now it works fine.

```c++
#include <cstdio>
#include <thread>
#include <condition_variable>
#include <mutex>
#include <chrono>

int main() {
    enum { COUNT = 1000000 };
    volatile int ping = 0, pang = 0;
    auto clock = std::chrono::high_resolution_clock::now();
    std::condition_variable cvPing, cvPang;
    std::mutex mtx;
    
    std::thread thd([&](){
        cvPing.notify_all();
        std::unique_lock<std::mutex> lock(mtx);
        while (pang < COUNT) {
            cvPang.wait(lock);
            ++pang;
            cvPing.notify_all();
        }
    });
    
    {
        std::unique_lock<std::mutex> lock(mtx);
        while (ping < COUNT) {
            cvPing.wait(lock);
            ++ping;
            cvPang.notify_all();
        }
    }
    
    thd.join();
    std::printf("PING: %d, PANG: %d, Time used: %lldms\n", ping, pang, (std::chrono::high_resolution_clock::now() - clock).count() / 1000000);
}
```

Note: I got 14430ms on my machine ( Win7, VM ) with the build downloaded on your site.

**Comment by lhmouse** [comment]
> Note: I got 14430ms on my machine ( Win7, VM ) with the build downloaded on your site.

Compare it with winpthread.

The program compiled using MSVC2015 hangs forever for unknown reasons.

**Comment by CarterLi** [comment]
> The program compiled using MSVC2015 hangs forever for unknown reasons.

I don't install MSVC. My program supposes that main thread sleeps before `cvPing.notify_all()` is called in work thread. Otherwise deadlock.

**Comment by CarterLi** [comment]
> The program compiled using MSVC2015 hangs forever for unknown reasons.

What about move `cvPing.notify_all();` after the lock in **pang** thread?

**Comment by lhmouse** [comment]
> What about move cvPing.notify_all(); after the lock in pang thread?

Your code doesn't look problematic. GCC didn't fail either.

**Comment by carlkl** [comment]
One stupid question: what is the right way to integrate the https://github.com/lhmouse/mcfgthread/tree/master/release/mingw64 release into say a mingw64 build with win32 threads?

I tried to compile https://github.com/lhmouse/mcfgthread/issues/15#issuecomment-236432906 with such a combination, but always end up with:

````
$ g++ -std=c++11 -I/__FULL-PATH__/include/mcfgthread/env mcfgthread_chrono.cxx
mcfgthread_chrono.cxx: In function 'int main()':
mcfgthread_chrono.cxx:11:5: error: 'condition_variable' is not a member of 'std'
     std::condition_variable cvPing, cvPang;
     ^
mcfgthread_chrono.cxx:12:5: error: 'mutex' is not a member of 'std'
     std::mutex mtx;
     ^
mcfgthread_chrono.cxx:14:5: error: 'thread' is not a member of 'std'
     std::thread thd([&](){
     ^
mcfgthread_chrono.cxx:22:6: error: expected primary-expression before ')' token
     });
      ^
mcfgthread_chrono.cxx:25:26: error: 'mutex' is not a member of 'std'
         std::unique_lock<std::mutex> lock(mtx);
                          ^
mcfgthread_chrono.cxx:25:26: error: 'mutex' is not a member of 'std'
mcfgthread_chrono.cxx:25:36: error: template argument 1 is invalid
         std::unique_lock<std::mutex> lock(mtx);
                                    ^
mcfgthread_chrono.cxx:25:42: error: invalid type in declaration before '(' token
         std::unique_lock<std::mutex> lock(mtx);
                                          ^
mcfgthread_chrono.cxx:25:43: error: 'mtx' was not declared in this scope
         std::unique_lock<std::mutex> lock(mtx);
                                           ^
mcfgthread_chrono.cxx:27:13: error: 'cvPing' was not declared in this scope
             cvPing.wait(lock);
             ^
mcfgthread_chrono.cxx:29:13: error: 'cvPang' was not declared in this scope
             cvPang.notify_all();
             ^
mcfgthread_chrono.cxx:33:5: error: 'thd' was not declared in this scope
     thd.join();
     ^
```
It seems I need something else than 
```C
#include <thread>
```
BTW: I'm able to compile and link a C11 C-program with such a combination using 
```C
#include <mcfgthread/c11thread.h>
```
instead of 
```C
#include <threads.h>
```

**Comment by lhmouse** [comment]
@carlkl

Short answer: It is not possible because it requires reconfiguring and rebuilding libstdc++.
For detailed discussion please open a new pull request.

Anyway you might want to take a look at <http://www.lhmouse.com/gcc-mcf/>.

**Comment by CarterLi** [comment]
Now I have a Windows environment ( bootcamped ) to test this. I fixed hang bug on VS, and test it on both compilers.

```cmd
C:\Users\Carter>type test.cpp
#include <cstdio>
#include <thread>
#include <condition_variable>
#include <mutex>
#include <chrono>

int main() {
    enum { COUNT = 1000000 };
    volatile int ping = 0, pang = 0;
    auto clock = std::chrono::high_resolution_clock::now();
    std::condition_variable cvPing, cvPang;
    std::mutex mtx;

    std::thread thd;
    {
        std::unique_lock<std::mutex> lock(mtx);

        thd = std::thread([&]() {
            std::unique_lock<std::mutex> lock(mtx);
            cvPing.notify_all();
            while (pang < COUNT) {
                cvPang.wait(lock);
                ++pang;
                cvPing.notify_all();
            }
        });

        while (ping < COUNT) {
            cvPing.wait(lock);
            ++ping;
            cvPang.notify_all();
        }
    }

    thd.join();
    std::printf("PING: %d, PANG: %d, Time used: %lldms\n", ping, pang, (std::chrono::high_resolution_clock::now() - clock).count() / 1000000);
}
C:\Users\Carter>g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.2.1/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../gcc/configure --prefix=/mingw64 --with-local-prefix=/mingw64/local --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --with-native-system-header-dir=/mingw64/x86_64-w64-mingw32/include --libexecdir=/mingw64/lib --enable-bootstrap --with-arch=x86-64 --with-tune=nocona --enable-languages=c,lto,c++ --enable-shared --enable-static --enable-threads=mcf --enable-graphite --enable-fully-dynamic-string --enable-libstdcxx-time=yes --disable-libstdcxx-pch --disable-libstdcxx-debug --disable-isl-version-check --enable-lto --enable-libgomp --disable-multilib --enable-checking=release --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --with-libiconv --with-system-zlib --with-gmp=/mingw64 --with-mpfr=/mingw64 --with-mpc=/mingw64 --with-isl=/mingw64 --with-pkgversion='gcc-6-branch HEAD with MCF thread model, built by LH_Mouse.' --with-bugurl=http://github.lhmouse.com/ --with-gnu-as --with-gnu-ld --disable-tls
Thread model: mcf
gcc version 6.2.1 20161117 (gcc-6-branch HEAD with MCF thread model, built by LH_Mouse.)

C:\Users\Carter>g++ test.cpp -O3 -march=native -std=c++14 -o mcf.exe

C:\Users\Carter>cl test.cpp -Ox /EHsc -Fevs.exe
用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.00.24215.1 版
版权所有(C) Microsoft Corporation。保留所有权利。

test.cpp
Microsoft (R) Incremental Linker Version 14.00.24215.1
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:vs.exe
test.obj

C:\Users\Carter>mcf
^C
C:\Users\Carter>vs
PING: 1000000, PANG: 1000000, Time used: 514ms

C:\Users\Carter>vs
PING: 1000000, PANG: 1000000, Time used: 489ms

C:\Users\Carter>mcf
PING: 1000000, PANG: 1000000, Time used: 50240ms

C:\Users\Carter>mcf
PING: 1000000, PANG: 1000000, Time used: 37500ms

C:\Users\Carter>mcf
PING: 1000000, PANG: 1000000, Time used: 36933ms

C:\Users\Carter>vs
PING: 1000000, PANG: 1000000, Time used: 476ms

C:\Users\Carter>vs
PING: 1000000, PANG: 1000000, Time used: 507ms

C:\Users\Carter>vs
PING: 1000000, PANG: 1000000, Time used: 518ms
```

As you can see @lhmouse , g++ with mcfthread enabled is about 100x slower than cl, any thought?

**Comment by lhmouse** [comment]
@CarterLi 

    E:\Desktop>a.exe
    PING: 1000000, PANG: 1000000, Time used: 3672ms
    
    E:\Desktop>a.exe
    PING: 1000000, PANG: 1000000, Time used: 4166ms
    
    E:\Desktop>a.exe
    PING: 1000000, PANG: 1000000, Time used: 4087ms
    
    E:\Desktop>cl /EHsc test.cpp /Oy
    用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.00.24213.1 版
    版权所有(C) Microsoft Corporation。保留所有权利。
    
    test.cpp
    Microsoft (R) Incremental Linker Version 14.00.24213.1
    Copyright (C) Microsoft Corporation.  All rights reserved.
    
    /out:test.exe
    test.obj
    
    E:\Desktop>test.exe
    PING: 1000000, PANG: 1000000, Time used: 782ms
    
    E:\Desktop>test.exe
    PING: 1000000, PANG: 1000000, Time used: 566ms

The problem might have something to do with the condition variable. A thread could spin for a while before it eventually makes a syscall.

**Comment by lhmouse** [comment]
In your previous example the program built by MSVC hang up forever, rendering the implementation of MSVC incorrect, in spite that it performed better than mcfgthread.

As users usually check the condition before they call `*_cond_wait()` actually, this could be a minor problem. Sadly at the moment I don't have much time to work on it.

**Comment by lhmouse** [comment]
@CarterLi 

I replaced `wait(lock)` with `wait_for(lock, std::chrono::hours(1))` and the program compiled by MSVC  degenerated much worse than that using mcfgthread:

    E:\Desktop>g++ test.cpp -O3
    
    E:\Desktop>a
    PING: 1000000, PANG: 1000000, Time used: 4134ms
    
    E:\Desktop>a
    PING: 1000000, PANG: 1000000, Time used: 4818ms
    
    E:\Desktop>a
    PING: 1000000, PANG: 1000000, Time used: 3995ms
    
    E:\Desktop>cl /EHsc /Ox test.cpp /nologo
    test.cpp
    
    E:\Desktop>test.exe
    PING: 1000000, PANG: 1000000, Time used: 2082ms
    
    E:\Desktop>test.exe
    PING: 1000000, PANG: 1000000, Time used: 2049ms
    
    E:\Desktop>test.exe
    PING: 1000000, PANG: 1000000, Time used: 2064ms
    
    E:\Desktop>

**Comment by CarterLi** [comment]
> In your previous example the program built by MSVC hang up forever, rendering the implementation of MSVC incorrect, in spite that it performed better than mcfgthread.

No. The problem is that code in PANG thread is somehow executed before the global mutex is locked in the main thread. It's a bug of my code.

> I replaced wait(lock) with wait_for(lock, std::chrono::hours(1)) and the program compiled by MSVC degenerated much worse than that using mcfgthread:

Really? 4134ms VS 2082ms?

**Comment by lhmouse** [comment]
@CarterLi 

>> I replaced wait(lock) with wait_for(lock, std::chrono::hours(1)) and the program compiled by MSVC degenerated much worse than that using mcfgthread:
>Really? 4134ms VS 2082ms?
... (degenerated much worse) than ...

**Comment by CarterLi** [comment]
my bad...

**Comment by lhmouse** [comment]
It didn't help much.

    E:\Desktop>g++ test.cpp -O3
    
    E:\Desktop>a
    PING: 1000000, PANG: 1000000, Time used: 4118ms
    
    E:\Desktop>a
    PING: 1000000, PANG: 1000000, Time used: 4243ms
    
    E:\Desktop>a
    PING: 1000000, PANG: 1000000, Time used: 4352ms
    
    E:\Desktop>cl /EHsc /Ox test.cpp /nologo
    test.cpp
    
    E:\Desktop>test.exe
    PING: 1000000, PANG: 1000000, Time used: 772ms
    
    E:\Desktop>test.exe
    PING: 1000000, PANG: 1000000, Time used: 628ms
    
    E:\Desktop>test.exe
    PING: 1000000, PANG: 1000000, Time used: 636ms

**Comment by lhmouse** [comment]
Oops, the code was wrong. I fixed it and it was much better.

    E:\Desktop>g++ test.cpp -O3
    
    E:\Desktop>a
    PING: 1000000, PANG: 1000000, Time used: 374ms
    
    E:\Desktop>a
    PING: 1000000, PANG: 1000000, Time used: 358ms
    
    E:\Desktop>a
    PING: 1000000, PANG: 1000000, Time used: 405ms

**Comment by CarterLi** [comment]
I don't think such an optimization should be put into the __low level code__ `ReallyWaitForConditionVariable`

p(g)thread level should be ok

**Comment by CarterLi** [comment]
What about put the code into your test case?
At least, we should ensure that `PING: 1000000, PANG: 1000000` is correctly printed

**Comment by lhmouse** [comment]
> I don't think such an optimization should be put into the low level code ReallyWaitForConditionVariable

The spin loop *must* be inserted after the lock callback.
The code needs some cleanup. And we have to introduce ABI incompatibility unless we are going to keep some Microsoft-style names such as `_MCFCRT_WaitForConditionVariableWithSpinCount()`.

**Comment by lhmouse** [comment]
> What about put the code into your test case?
> At least, we should ensure that PING: 1000000, PANG: 1000000 is correctly printed

It is.

> I don't think such an optimization should be put into the low level code ReallyWaitForConditionVariable

One more word: We try our best to keep the mutex/cond var/once flag itself as **slim** as possible (just as how M$ people describe their own ones). As a result, the spin count can't be stored inside these objects and has to be passed explicitly as a parameter.

**Comment by lhmouse** [comment]
https://github.com/lhmouse/mcfgthread/pull/17
