### ISSUE TITLE
Should we implement `GetTickCount64()` for Windows XP?

### ISSUE THREAD

**Issue by lhmouse** [lhmouse/mcfgthread#16]
This is the only obstacle on our way to Windows XP support, at the moment.

**Comment by FrankHB** [comment]
Considerable.

**Comment by lhmouse** [comment]
@revelator 

Just tested on Windows XP:
`NtWaitForKeyedEvent` does not accept a null handle on Windwos XP while on Windows 7 a null handle designates a potentially pre-allocated keyed event. This renders mcfgthread unusable on Windows XP.

**Comment by void2012** [comment]
@lhmouse Regarding the `NtWaitForKeyedEvent`: Can we allocate a key event per each synchronization object? No? Am I missing something?
```cpp
HANDLE hKeyedEvent;
NtCreateKeyedEvent(&hKeyedEvent, KEYEDEVENT_ALL_ACCESS, NULL, 0);
```

Because it looks like `KernelObjects\CritSecOutOfMemoryEvent` is rather an emergency wait event?

**Comment by void2012** [comment]
By the way, can you hint me on this matter:

1. I found this GetTickCount64 implementation across the internet, on my machine this gives me the same result as the native kernel32 GetTickCount64, but I'm not sure how reliable this is:
```c
uint64_t XP_GetTickCount64() 
{
    static volatile long hi = 0;
    static volatile long last_lo = 0;
    
    uint32_t lo = GetTickCount();
    
    long captured_hi;
    long captured_last_lo;
    
    for (;;) {
        captured_hi = _InterlockedCompareExchange(&hi, 0, 0);
        captured_last_lo = _InterlockedCompareExchange(&last_lo, 0, 0);
        
        if (lo >= (uint32_t)captured_last_lo) {
            long current_hi = _InterlockedCompareExchange(&hi, 0, 0);
            if (current_hi == captured_hi) {
                _InterlockedCompareExchange(&last_lo, (long)lo, captured_last_lo);
                return ((uint64_t)captured_hi << 32) | lo;
            }
            continue;
        }
        
        if (_InterlockedCompareExchange(&last_lo, (long)lo, captured_last_lo) == captured_last_lo) {
            captured_hi = _InterlockedIncrement(&hi);
            return ((uint64_t)captured_hi << 32) | lo;
        }
    }
}
```

2. Is the `QueryUnbiasedInterruptTime` precision really matters (`xglobals.c`)? Can I replace it with `QueryPerformanceCounter` or the `XP_GetTickCount64` mentioned above for Windows XP? Any caveats?
