### ISSUE TITLE
Support for clang++ and libcxx?

### ISSUE THREAD

**Issue by lhmouse** [lhmouse/mcfgthread#18]
Should we add support for clang++ and libcxx on Windows?

If somebody wants to contribute, [here](http://llvm.org/svn/llvm-project/libcxx/trunk/include/__threading_support) is some pseudo documentation.

**Comment by FrankHB** [comment]
Worth trying.

**Comment by lhmouse** [comment]
@FrankHB 

make it happen? :joy:

**Comment by FrankHB** [comment]
If I had time...
-1s :(

**Comment by CarterLi** [comment]
Does this project have any problems compiling with clang on windows?

And what the target is? `mingw-w64`? `msvc`?

**Comment by lhmouse** [comment]
@CarterLi
There might be. I haven't tested it yet.

**Comment by lhmouse** [comment]
See <http://lists.llvm.org/pipermail/cfe-dev/2017-March/053339.html>.

**Comment by CarterLi** [comment]
https://gcc.godbolt.org can generate Intel-style ASM somehow
https://godbolt.org/g/MyraQx

**Comment by lhmouse** [comment]
That is irrelevant. The problem is that at the moment [_seg_top.h](https://github.com/lhmouse/mcfgthread/blob/master/src/env/_seh_top.h) doesn't compile on clang for i686. On x64 there is no problem because the AT&T and Intel syntaxes happen to be the same.

**Comment by vyache76** [comment]
not sure but 
`    __asm__ volatile (`
`      "mov{l} {%%fs:0, %0|%0, dword ptr fs:[0]} \n"`
`      "mov{l} {%0, (%1)|dword ptr[%1], %0} \n"`
`      "mov{l} {%2, 4(%1)|dword ptr[%1 + 4], %2} \n"`
`      "mov{l} {%1, %%fs:0|dword ptr fs:[0], %1} \n"`
`      : "=&r"(__pUnused) : "r"(__pSehNode), "p"(__MCFCRT_SehTopDispatcher)`
`    );`
`
will generate the same code for at&t and Intel syntax?

**Comment by lhmouse** [comment]
I suspect that's correct.

At the moment we have [`-masm=intel`](https://github.com/lhmouse/mcfgthread/blob/c446cf4fcdc262fc899a188a4bb7136284c34222/Makefile.am#L6) which should be removed first. PRs are welcome.

**Comment by lhmouse** [comment]
> 
> will generate the same code for at&t and Intel syntax?

https://github.com/lhmouse/mcfgthread/blob/12c53d5a8b396caec688511ecf14af0ca6e980e2/src/win32.h#L127

It seems there is no way to make clang accept Intel syntax, so I decide to stick with AT&T syntax, and leave Intel syntax in comments. This piece of assembly was actually created by disassembling GCC's output with GDB.

**Comment by lhmouse** [comment]
This is the last error that is blocking Clang support:  https://github.com/llvm/llvm-project/issues/55329
