### ISSUE TITLE
Why bother GCC guys? Please try to merge this info MinGW-w64 mainline.

### ISSUE THREAD

**Issue by CarterLi** [lhmouse/mcfgthread#2]
It doesn't seem that GCC guys care about Windows mush. It's the business of MinGW.
http://mingw-w64.org/doku.php/contribute#c11_and_c_11_threading_support

飞翔的天地

**Comment by lhmouse** [comment]
C++0x threading should be working now.
I am currently implementing the C11 counterpart and there are a few differences.
Once it is done I am ready to call for tests.

**Comment by FrankHB** [comment]
Kai Tietz *is* one of "GCC guys".

**Comment by lhmouse** [comment]
@FrankHB 

[JonY has been one, too](https://gcc.gnu.org/ml/gcc/2016-06/msg00073.html).

**Comment by FrankHB** [comment]
Yeah. So I did not say "the only one".

I once heard there was only one people responsible for mingw32 target in GCC team.

**Comment by CarterLi** [comment]
>  I need JonY and ktietz's opinion at the moment.

Well, good luck

**Comment by lhmouse** [comment]
Updated.

**Comment by CarterLi** [comment]
For promotion, we may upload your build to [the official MinGW-w64 repository](https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/). Maybe a bit early, you may also try to submit a PR [here](https://github.com/Alexpux/MINGW-packages/pulls)

**Comment by lhmouse** [comment]
@CarterLi 

I would not do that until we have an RC.
