### ISSUE TITLE
You can never defeat builtins in special cases.

### ISSUE THREAD

**Issue by CarterLi** [lhmouse/mcfgthread#23]
For example, memcpy for small buffer: https://godbolt.org/g/AkekLW
And buffers for memcpy with constant size are usually small and aligned

So don't [do that](https://github.com/lhmouse/mcfgthread/commit/a8106b5b8ad24918a7012414970d40d83672e9fa).

**Comment by lhmouse** [comment]
1. We don't have anything newer than SSE2 enabled.  
2. We have `-ffree-standing` enabled so a function call is a function call. If we have a call to `memcpy()` or `__builtin_memcpy()` it results in an external call to that function.  

Hardcoding inline versions of these functions might sound a bad idea, but it is an effective way to prevent GCC from generating such external function calls completely.

**Comment by CarterLi** [comment]
* Why do we use `-ffree-standing` in such a lib for multi-threading?
* Why we can call external Win32 APIs but an standard & general used C API?

**Comment by lhmouse** [comment]
I have been carefully checking use of these functions. We do have better solutions (indeed SSE2 is a lot better) but it can't be enabled on x86 for historical reasons.

**Comment by CarterLi** [comment]
We already drop XP/Vista. I see no reason to drop CPUs that don't support SSE2

**Comment by CarterLi** [comment]
And don't align memory manually when given pointer is not aligned. Just use `*loadu*` functions directly. They do have the same performance in modern CPUs. 
https://software.intel.com/sites/landingpage/IntrinsicsGuide/#cats=Load,Store&techs=SSE2&expand=3144,3083

**Comment by lhmouse** [comment]
> Why do we use -ffree-standing in such a lib for multi-threading?
> Why we can call external Win32 APIs but an standard & general used C API?

That is because MSVCRT is unavailable. NTDLL does have many C library functions exported however I just want to get them out of my sight. This is true even for MCRCRT which has basically three versions of `memcpy()` (an inline version using `rep movs` and inline and external versions using SSE2).

XP support was dropped, but Vista support [was not](https://msdn.microsoft.com/en-us/library/windows/desktop/ms724411(v=vs.85).aspx) despite being completely untested.

MSYS2 doesn't enable SSE2 for i686 and I have to follow that. Note that Intel is still selling super tiny x86 CPUs that even don't have SSE.

**Comment by lhmouse** [comment]
> And don't align memory manually when given pointer is not aligned. Just use *loadu* functions directly. They do have the same performance in modern CPUs.

This is only true if the number of instructions is bounded.

**Comment by CarterLi** [comment]
> That is because MSVCRT is unavailable.

That it not the case. 99% of people that use pthread ( mcfgthread in this case ) will use standard C apis. For MinGW MSVCRT is always linked.

> MSYS2 doesn't enable SSE2 for i686

OMG... So let's include `#ifndef` venders...

**Comment by lhmouse** [comment]
> That it not the case. 99% of people that use pthread ( mcfgthread in this case ) will use standard C apis. For MinGW MSVCRT is always linked.

[I disabled it](https://github.com/lhmouse/mcfgthread/blob/master/Makefile.am#L97).

> OMG... So let's #ifndef

No just keep the `rep movs` version. It is generic and efficient enough for small chunks of bytes.

**Comment by CarterLi** [comment]
Summary:
1.  You add another two functions, which means larger code base, larger binary, maybe more bugs.
1.  You don't use builtins instead write it yourself, which means you prevent the chance for compiler from optimizing the code. In addition, compiler can't assume that buffers are zero-cleaned or copied, which may prevent other optimizations.
1.  You use inline asm, which means your code is harder to migrate.

**Comment by lhmouse** [comment]
> You add another two functions, which means larger code base, larger binary, and maybe more bugs.

There may be. There ain't going to be. There is a maintainer.

> You don't use builtins instead write it yourself, which means you prevent the chance for compiler from optimizing the code.

I don't want it to.

> In addition, compiler can't assume that buffers are zero-cleaned or copied, which may prevent other optimizations.

At the moment, GCC doesn't produce better code given the assumption. I don't think it is going to, either.

> You use inline asm, which means your code is harder to migrate.

Basically: I don't care. The code is designed for x64 and x86, and will work on x64 and x86, period. If someone wants to port code to other platforms, just do it. I appreciate it.

> I see no reason for such a performance-oriented project to do such a bad thing.

Is it? We are being semantically correct by adding `-ffree-standing` just because MSVCRT isn't there despite the fact that NTDLL exports `memcpy()` (which is a synonym of `RtlCopyMemory()` ) and `memset()`, aren't we? The result is that `__builtin_memcpy()` and `__builtin_memset()` always create function calls that can't be inlined at all, so we have to implement inline ones ourselves. In reality, the inline versions in mcfgthread take up less room and don't contain any branches at all, surpassing the inline ones generated by GCC.

**Comment by CarterLi** [comment]
Well...
Are those functions provided by NTDLL that awful? So why do they provide such a function instead of using the highly optimised one provided by MSVCRT? For stability or something?
Instead of providing a new function, can we NTR NTDLL by using the same function name?

**Comment by lhmouse** [comment]
Such functions provided by NTDLL are usually stable and not so optimized as those provided MSVCR???.

I pushed a more optimized version of inline_mem.h. See <https://godbolt.org/g/4mJ2P0>.

**Comment by lhmouse** [comment]
> Well...
> Are those functions provided by NTDLL that awful? So why do they provide such a function instead of using the highly optimised one provided by MSVCRT? For stability or something?

Microsoft people do have their own consideration.
On modern Intel CPUs you can do `memcpy` with a brute `rep movsb` and gain maximum throughput that your hardware allows - this is not the case for `movsw` whatsoever. Is anyone willing to do that? I don't think so.

> Instead of providing a new function, can we NTR NTDLL by using the same function name?

No comments.

**Comment by CarterLi** [comment]
> Microsoft people do have their own consideration.
On modern Intel CPUs you can do memcpy with a brute rep movsb and gain maximum throughput that your hardware allows - this is not the case for movsw whatsoever. Is anyone willing to do that? I don't think so.

I have never watched the memcpy disasm provided by NTDLL because I dont know how to call them directly in my code. Im just guessing. But i have watched the disasm lstrlen(A/W), plain loop is used even without basic unlooping optimizion.

The question is: If the functions provided by NTDLL is fullly optimized, why dont you use them.

Ps: i dont think you have to rep movsb if you need only one mov

**Comment by lhmouse** [comment]
> I have never watched the disasm of memcpy provided by NTDLL because I dont know how to call it directly in my code.

Add `-lntdll` into the command line before anything else, or use `LoadLibrary()` + `GetProcAddress()`.

> Im just guessing. But i have watched the disasm of lstrlen(A/W), plain loop is used even without basic unlooping optimizion.

On modern processors manual loop unrolling helps little.
Nevertheless you might want to have a look at [this](https://github.com/lhmouse/MCF/blob/master/MCFCRT/src/ext/rawmemchr.c). `strlen(s)` is effectively `(size_t)(rawmemchr(s, 0) - s)`. There is [a variant](https://github.com/lhmouse/MCF/blob/master/MCFCRT/src/ext/rawwmemchr.c) for `rawwmemchr()` too.

> The question is: If the functions provided by NTDLL are fullly optimized, why do you refuse to use them.

They aren't. At least they can't be inlined.

> Ps: i dont think you have to rep movsb if you need only one mov or two

As a compiled function it just can't know how many bytes to copy/fill. There is no silver bullet.

**Comment by CarterLi** [comment]
> The result is that __builtin_memcpy() and __builtin_memset() always create function calls that can't be inlined at all, so we have to implement inline ones ourselves. In reality, the inline versions in mcfgthread take up less room and don't contain any branches at all, surpassing the inline ones generated by GCC.

It turn out that GCC can generate `stosqq and friends:
https://godbolt.org/g/gb1Nmb
It seems that GCC tries to align pointer to QWORD for unknown pointers. is it required by `stosq`?
For buffers known at compile time. GCC even knows how many bytes remains and correctly generates `mov` unlike what you did.

**Comment by CarterLi** [comment]
> Nevertheless you might want to have a look at this.

Yes I did it several years ago. But you can't do it since

> MSYS2 doesn't enable SSE2 for i686

-_-

**Comment by CarterLi** [comment]
> On modern Intel CPUs you can do memcpy with a brute rep movsb and gain maximum throughput that your hardware allows - this is not the case for movsw whatsoever. Is anyone willing to do that? I don't think so.

There is one: https://godbolt.org/g/lKXWoF

**Comment by lhmouse** [comment]
> It seems that GCC tries to align pointer to QWORD for unknown mem addresses. is it required by stosq?

As required by x86 which handles unaligned memory access transparently, no. But unaligned access might be slow. It could be probably the case on some AMD and some old Intel processors, but apparently it isn't the case on mine (aligned and unaligned `stosq` are equally fast).

> Which version of GCC are you using?

gcc-6-branch HEAD with `-O3 -ffreestanding`.

>>This is only true if the number of instructions is bounded.
> Citation needed

If there are an indeterminate number of instructions you would have to create a loop to do that, then `movdqu` would be a bit slower than `movdqa` (nevertheless it would not be any faster). If you are sure you only need two moves of DQWORDs then two `movdqu` would probably be faster than aligning the pointer + copying unsligned bytes + copying a DQWORD with `movdqa`.

**Comment by CarterLi** [comment]
> gcc-6-branch HEAD with -O3 -ffreestanding.

Tested with `-ffreestanding`; GCC won't generate `memset` call. There must be something wrong with your compiler.

**Comment by lhmouse** [comment]
If these two instructions were equivalent fast, Intel people wouldn't bother themselves to create an additional one at the cost of more transistors and more power consumption. The `movdqu` instruction isn't necessarily slower, but it **might be**. There are a handful of articles about unaligned memory access with SIMD, for example, [this on software.intel.com](https://software.intel.com/en-us/articles/reducing-the-impact-of-misaligned-memory-accesses/).

**Comment by lhmouse** [comment]
>> gcc-6-branch HEAD with -O3 -ffreestanding.
> Tested with -ffreestanding; GCC won't generate memset call. There must be something wrong with your compiler.

GCC will not, if the number of bytes is known and is not very large during compile time. It will generate a function if the number can't be predicted, for example, when it comes from a function parameter.

**Comment by CarterLi** [comment]
Yes, maybe core2 or P4, maybe AMDs. But the problem is: for buffers on stack pointers are usually aligned its ok; for buffers alloced in heap, they are usually unassigned (Because of new and few people are aware of aligned_malloc) but padded. In this case if you must align the pointer, extra ugly movs are needed which results in ugly code. You dont like them, do you?

For buffer size which are known on compile time, wo wont bother optimising them. Just call memset/memcpy.

**Comment by lhmouse** [comment]
> for buffers alloced in heap, they are usually unassigned (Because of new and few people are aware of aligned_malloc) but padded. 

The pointer returned by a successful `malloc()`, `calloc()` or `realloc()` function call must be aligned such that _it may be assigned to a pointer to any type of object with a fundamental alignment requirement and then used to access such an object or an array of such objects in the space allocated (until the space is explicitly deallocated)_ (See _ISO/IEC WG14 N1570_, 7.22.3 Memory management functions).

**Comment by CarterLi** [comment]
> It will generate a function call if the number can't be predicted, for example, when it comes from a function parameter.

If no more info at compile time, no more opimization can be done after inlining, except larger binary. So why do you insist inlining them?

**Comment by CarterLi** [comment]
> The pointer returned by a successful malloc(), calloc() or realloc() function call must be aligned

Aligned to what? 8 for x86? Doesn't help

**Comment by lhmouse** [comment]
> If no more info at compile time, no more opimization can be done after inlining, except larger binary. So why do you insist inlining them?

In the case of C11 thread and gthread there are only a few bytes to copy so a call to external function is overkilling.

> Aligned to what? 8 for x86? Doesn't help

We just assume everything is properly aligned.

**Comment by CarterLi** [comment]
Let's stop this meaningless arguing.

Just see the rep* families: http://www.felixcloutier.com/x86/REP:REPE:REPZ:REPNE:REPNZ.html

It seems that they are born for mem* functions. Besides `rep movs` and `rep stos`

1.  `repne scas`: memchr
1.  `repe cmps`: memcmp

It doesn't seem that GCC can generate those instructions with `__builtin`s, it will be much more meaningful to implement them ourselves.

And `rep lods`, don't know it's usecase...

**Comment by lhmouse** [comment]
> And rep lods, don't know it's usecase...

It might be useful without `rep`.

**Comment by CarterLi** [comment]
> On modern Intel CPUs you can do memcpy with a brute rep movsb and gain maximum throughput that your hardware allows - this is not the case for movsw whatsoever. Is anyone willing to do that? I don't think so.

![image](https://cloud.githubusercontent.com/assets/6134068/25070264/8ef013d6-22cc-11e7-9f02-3fbcaf109288.png)

Oh god! M$ do this with their memset implementation and call it __Enhanced Fast Strings__...

**Comment by lhmouse** [comment]
@CarterLi 

See **3.7.6 Enhanced REP MOVSB and STOSB operation (ERMSB)** in <http://www.intel.com/content/dam/doc/manual/64-ia-32-architectures-optimization-manual.pdf>.

**Comment by CarterLi** [comment]
Yes @lhmouse 

Just googled this: http://stackoverflow.com/questions/33480999/how-can-the-rep-stosb-instruction-execute-faster-than-the-equivalent-loop#answer-33485055

It's CPU (hardware) level optimisation, OMG
