### ISSUE TITLE
can the benchmarking results also include wine?

### ISSUE THREAD

**Issue by yshui** [lhmouse/mcfgthread#243]
just out of curiosity of how wine compares. can you include wine's CRITICAL_SECTION and SRWLOCK implementation in your benchmarks as well?

thanks.

**Comment by lhmouse** [comment]
Yes, of course.

**Comment by lhmouse** [comment]
I don't have a 'suitable' physical machine for this benchmarking purpose. I thought a laptop was too constrained so I misappropriated a virtual server for one hour. It's done now: https://github.com/lhmouse/mcfgthread?tab=readme-ov-file#benchmarking

**Comment by yshui** [comment]
thank you so much
