### ISSUE TITLE
Should we migrate gcc from winpthreads to mcfgthread?

### ISSUE THREAD

**Issue by UsmanTariq2** [lhmouse/mcfgthread#251]

**Comment by lhmouse** [comment]
Here's some random stuff:

1. boost seems to use `std::`, so no action is to be taken.
2. Python and mostly others have dedicated Windows native implementation and do not depend on winpthread, so no action is to be taken, either.
3. libgomp, as part of GCC runtime libraries, asks for pthread explicitly, so code needs to be rewritten. I don't know how much work there is.
