### ISSUE TITLE
Issue on symbols

### ISSUE THREAD

**Issue by FrankHB** [lhmouse/mcfgthread#3]
Some symbol names might be unnecessarily too long, e.g. `*tag*`.

To make the ABI stable, source level symbol versioning should be considered, e.g. `inline namespace` and ABI tags. (However, this might make the symbol names longer.)

**Comment by lhmouse** [comment]
C++ name mangling is out of question here since we do not have ANY C++ code at the moment.

**Comment by FrankHB** [comment]
I was not talking about name mangling. Even without decoration the plain symbol names are already that long.

**Comment by lhmouse** [comment]
I don't think it matters. The symbol in question, despite the length of its name, isn't meant to go anywhere into binary code.

**Comment by FrankHB** [comment]
Sounds plausible as long as not used standalone. OK.
