### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by eMosbat** [lhmouse/mcfgthread#30]
I am geting this error in ubuntu 16.04:

root@ubuntu:/home/coin/mcfgthread# make
make  all-am
make[1]: Entering directory '/home/coin/mcfgthread'
depbase=`echo src/dll_startup.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I.  -Wall -Wextra -pedantic -pedantic-errors -Werror -Wno-error=unused-parameter -Winvalid-pch -Wwrite-strings -Wconversion -Wsign-conversion -Wdouble-promotion -Wsuggest-attribute=noreturn -Wundef -Wshadow -Wstrict-aliasing=2 -pipe -mno-stack-arg-probe -masm=intel -ffreestanding  -include __pch.h -std=c11 -Wstrict-prototypes -g -O2 -MT src/dll_startup.o -MD -MP -MF $depbase.Tpo -c -o src/dll_startup.o src/dll_startup.c &&\
mv -f $depbase.Tpo $depbase.Po
In file included from src/mcfcrt.h:24:0,
                 from src/dll_startup.c:5:
src/env/thread.h:12:1: error: â__stdcall__â attribute ignored [-Werror=attributes]
 typedef unsigned long (__attribute__((__stdcall__)) *_MCFCRT_NativeThreadProc)(
 ^
In file included from src/env/_seh_top.h:9:0,
                 from src/dll_startup.c:6:
src/env/mcfwin.h:30:21: fatal error: windows.h: No such file or directory
cc1: all warnings being treated as errors
compilation terminated.
Makefile:637: recipe for target 'src/dll_startup.o' failed
make[1]: *** [src/dll_startup.o] Error 1
make[1]: Leaving directory '/home/coin/mcfgthread'
Makefile:417: recipe for target 'all' failed
make: *** [all] Error 2
root@ubuntu:/home/coin/mcfgthread#

**Comment by lhmouse** [comment]
Apparently you are compiling using the command `gcc`, which invokes the native compiler for Ubuntu.

Since this project targets Windows you must specify a cross compiler. That is, you **have to** specify the `--host=` option to `./configure`. Use `--host=i686-w64-mingw32` for x86 and `--host=x86_64-w64-mingw32` for x64, respectively.

**Comment by lhmouse** [comment]
We have a not-so-nice example of cross-compiling from Ubuntu: <https://github.com/lhmouse/mcfgthread/blob/master/.travis.yml>

Unquote double quotes to get the commands. They shall run fluently in bash.
