### ISSUE TITLE
[Not about MCF] mingw-w64.org certificate has been expired for weeks

### ISSUE THREAD

**Issue by zufuliu** [lhmouse/mcfgthread#42]
open https://mingw-w64.org/doku.php

Firefox:
It’s likely the website’s certificate is expired, which prevents Firefox from connecting securely. If you visit this site, attackers could try to steal information like your passwords, emails, or credit card details.

Chrome:
Your connection is not private
Attackers might be trying to steal your information from mingw-w64.org (for example, passwords, messages, or credit cards). Learn more
NET::ERR_CERT_DATE_INVALID

**Comment by lhmouse** [comment]
better report this on IRC or mailing list cuz I am not the guy who maintains our website. :smiley:

**Comment by zufuliu** [comment]
Don't known which list to use, I added a bug at https://sourceforge.net/p/mingw-w64/bugs/812/
the plain HTTP version works: http://mingw-w64.org/doku.php

If I remember correctly, the website previously use Let's Encrypt certificate, which I think should auto-renew.

**Comment by lhmouse** [comment]
Use [this](mailto:mingw-w64-public@lists.sourceforge.net).

**Comment by zufuliu** [comment]
Possible you can forward it? it likely no one is watching your bug list.
```
Your mail to 'Mingw-w64-public' with the subject

    bugs#812 mingw-w64.org certificate has been expired for weeks

Is being held until the list moderator can review it for approval.

The reason it is being held:

    Post by non-member to a members-only list
```

**Comment by lhmouse** [comment]
OK I noted this on IRC.
