### ISSUE TITLE
gcc-mcf.lhmouse.com is inaccessible

### ISSUE THREAD

**Issue by Ptomaine** [lhmouse/mcfgthread#46]
The gcc-mcf.lhmouse.com web site is inaccessible.

**Comment by lhmouse** [comment]
How so? It's working pretty well here. <https://gcc-mcf.lhmouse.com/>

**Comment by Ptomaine** [comment]
> How so? It's working pretty well here. https://gcc-mcf.lhmouse.com/

Weird :) It's available now :) Sorry for making some noise :)

**Comment by lhmouse** [comment]
Yeah, please close this issue. :)
