### ISSUE TITLE
Question about thread.c

### ISSUE THREAD

**Issue by CarterLi** [lhmouse/mcfgthread#57]
It uses [CreateThread](https://github.com/lhmouse/mcfgthread/blob/master/src/thread.c#L60)

However MSDN suggests using _beginthreadex when a thread calls the C run-time library (CRT) which I assume everyone ( that has Win32 programming experience ) knows.

Why did you do that?

**Comment by lhmouse** [comment]
**mcfgthread** is linked against no CRT, so those functions don't exist.

**Comment by CarterLi** [comment]
However programs that use your lib call those functions

For example: https://github.com/lhmouse/mcfgthread/blob/master/mutex_performance.c#L96

**Comment by lhmouse** [comment]
If you link against the CRT as a DLL (such MSVCRT or UCRT) then there is no problem or leak whatsoever. It only makes a difference if you link against a static CRT.

**Comment by CarterLi** [comment]
> If you link against the CRT as a DLL (such MSVCRT or UCRT) then there is no problem or leak whatsoever. It only makes a difference if you link against a static CRT.

citation needed

**Comment by lhmouse** [comment]
Why don't you read UCRT source yourself? If you have Windows SDK install you should have had it.
