### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by lazka** [lhmouse/mcfgthread#69]
https://github.com/lhmouse/mcfgthread/blob/master/LICENSE.TXT

* The first paragraph says public domain + LGPL without a version or if it is the "or-later" variant.
* The second paragraph says  GPL-3.0-or-later
* Then GPL and LGPL are included

Could this be made more clear maybe?

**Comment by lhmouse** [comment]
Originally only the formal text of LGPL v3 was included. As LGPL references GPL, I was a bit unsure whether it would suffice, so a copy of GPLv3 was also added in front of it.

The second paragraph was a mistake. It should reference LGPL instead of GPL. Thanks for pointing this out. I'll fix it.

**Comment by lazka** [comment]
thanks. the LGPL is self contained, so no need to reference the GPL.

**Comment by lhmouse** [comment]
I thought so until I saw this[^1]:

> If you are releasing your program under the Lesser GPL, you should also include [the text version of the LGPL](https://www.gnu.org/licenses/lgpl.txt), usually in a file called COPYING.LESSER. Please note that, since the LGPL is a set of additional permissions on top of the GPL, it's crucial **to include both licenses** so users have all the materials they need to understand their rights.

[^1]: https://www.gnu.org/licenses/gpl-howto.en.html

**Comment by lazka** [comment]
oh, sorry, good to know
