### ISSUE TITLE
libstdc++ recursive_mutex test is failing

### ISSUE THREAD

**Issue by lhmouse** [lhmouse/mcfgthread#8]
[This test](https://gcc.gnu.org/viewcvs/gcc/trunk/libstdc%2B%2B-v3/testsuite/30_threads/recursive_mutex/unlock/1.cc?view=markup) from libstdc++ is failing.
(A copy of the source file could be obtained [here](https://github.com/lhmouse/mcfgthread/files/347062/1.cc.txt) in case of URL expiration.)

This faulty test tries to unlock an unlocked recursive_mutex, which is definitely [undefined behavior](http://en.cppreference.com/w/cpp/language/ub). Specifically with **mcfgthread**, this causes assertion failure if `NDEBUG` had not been defined when the library was built.

It is GNU people that shall fix it.

**Comment by CarterLi** [comment]
Why not fire a bug to GCC guys?

**Comment by lhmouse** [comment]
> Why not fire a bug to GCC guys?

It is the guy who wrote this test that shall be fi**r**ed. XD XD XD

I didn't fi**l**e a bug report. Instead I sent a [mail](https://gcc.gnu.org/ml/gcc/2016-06/msg00062.html) to them. The mail effectively fell on deaf ears.

**Comment by CarterLi** [comment]
Oh my poor English...

You'd better fi**l**e a bug since mails are usually ignored by developers.
Otherwise, you should send a email to [libstdc++ mailing lists](https://gcc.gnu.org/ml/libstdc++/). It has no business with GCC compiler itself.

**Comment by lhmouse** [comment]
I don't think anybody is going to say a word about it. The libstdc++ testsuites are **terrible**.

**Comment by CarterLi** [comment]
You say it?
@Jonathan Wakely 😂

**Comment by lhmouse** [comment]
😂😂😂

**Comment by lhmouse** [comment]
I will close this issue as soon as I finish our new test suites.
