### ISSUE TITLE
Add cmake based build system

### ISSUE THREAD

**Issue by PHdrr** [lhmouse/mcfgthread#84]
For standalone MinGW like https://winlibs.com/

**Comment by lhmouse** [comment]
No, that is not going to happen.

**Comment by PHdrr** [comment]
> No, that is not going to happen.

Why?

**Comment by lhmouse** [comment]
It would be a new build-time dependency which solves no issue.

Although I don't include generated scripts in Git, it is always possible to run `make distcheck` and get a tarball of source code that requires only a working compiler and a shell.

**Comment by PHdrr** [comment]
> * Building mingw-64 requires a shell.
> * Building binutils also requires a shell.
> * Building GCC also requires a shell.
> 
> So what do you expect without a shell? Why would you build mcfgthread without GCC nor CRT?

So I need to build mingw-w64, binutils and gcc from source to use this library? How awful! I only think it's as an alternative thread library that I could link with instead of pthread (libwinpthread-1.dll).

**Comment by FrankHB** [comment]
> So I need to build mingw-w64, binutils and gcc from source to use this library? How awful! I only think it's as an alternative thread library that I could link with instead of pthread (libwinpthread-1.dll).

This is [already upstreamed in GCC 13](https://gcc.gnu.org/git/?p=gcc.git;a=commit;h=f036d759ecee538555fa8c6b11963e4033732463), although [the documentation](https://gcc.gnu.org/install/configure.html) is not update-to-date. Use [distro like this](https://gcc-mcf.lhmouse.com/) if you want prebuilt binary. Note that the produced binary images are not totally compatible to the result from toolchain with other thread models, so you cannot expect it would just work with your current toolchain configured differently.
