### ISSUE TITLE
Link issues using LLVM/Clang built to use GCC's standard libraries

### ISSUE THREAD

**Issue by brechtsanders** [lhmouse/mcfgthread#85]
@lhmouse can you take a look at https://github.com/brechtsanders/winlibs_mingw/issues/147 ?

When building LLVM/Clang to use GCC's standard libraries there are unresolved symbols related to MCF when linking.

**Comment by lhmouse** [comment]
I don't see clang++ in winlibs packages. Where do they get clang, from winlibs or somewhere elase?

**Comment by lhmouse** [comment]
I have explained the reason in https://github.com/brechtsanders/winlibs_mingw/issues/147#issuecomment-1536977552.

Maybe I should say that compiling with a compiler of the `posix` thread model and linking against a standard library of the `mcf` thread model is not supported, not just about linking statically.

There was an attempt to also add `mcf` thread model to clang which it was incomplete.

**Comment by brechtsanders** [comment]
> I don't see clang++ in winlibs packages. Where do they get clang, from winlibs or somewhere elase?

There are winlibs packages with both GCC and LLVM.

Thanks for your explanation. I hope MCF threads make it into LLVM some day, because I do think it's an improvement.
