### ISSUE TITLE
Blue screen crashes

### ISSUE THREAD

**Issue by brechtsanders** [lhmouse/mcfgthread#88]
Recently I have been using winlibs builds both with POSIX and MCF threads.
I have seen many bluescreen crashes on my Windows 11 build systems during this time.

A few days ago GCC 13.2.0 was released, so I started building the winlibs build of this release.
This time I decided to not build a lot of stuff at the same time but start with only the POSIX build and the MCF build later.

To my surprise the building the POSIX stuff survived the night and was still at it in the morning (I need this much time because I really build all dependencies from source). The build was a success (I published the UCRT build [here](https://github.com/brechtsanders/winlibs_mingw/releases/tag/13.2.0-16.0.6-11.0.0-ucrt-r1)).

Today I started the MCF build and my system already crashed multiple times.In Event viewer I see somerhing like this:
```
The computer has rebooted from a bugcheck.  The bugcheck was: 0x0000001a (0x0000000000000403, 0xffff9f00e106a360, 0x800000045c816867, 0x0000000000000000). A dump was saved in: C:\Windows\Minidump\072923-8968-01.dmp. Report Id: 77efbeef-e691-4404-be59-1ee047af32b8.
```

Apart from bluescreen crashes the system may also become unstable in other ways. Specifically GCC returning errors like:
```
internal compiler error: Segmentation fault
```
But when restarting that build it would sometimes proceed anyway, but sometimes not unless I put less load on the system by running `make -j1` or `ninja -j1`.
This typically happens when a lot of (build) processes are running simultaneously, typically generating 100% CPU load (in my build system's case across all 32 logical processors).

In the last weeks I had already tried a lot of stuff to avoid the crashes assuming it was hardware (disabled Turbo overclocking, lowered RAM frequency, disabled C sleep state, limited the maximum CPU temperature, ...) but nothing helped.

Now it seems clear to me that avoiding MCF altogether fixes the issue.
So for now I won't build MCF winlibs builds.

Is there anything that can be done about this issue?

**Comment by lhmouse** [comment]
This seems very unusual. I suspect it might have something to do with changes to the NT kernel in Windows 11. I have been building GCC for years from Windows 7 to Windows 10 and have never seen such an issue. Does this issue happen on Windows 10 too?

**Comment by lhmouse** [comment]
### Standard Windows APIs that mcfgthread uses

* `CreateThread`
* `EncodePointer`
* `ExitThread`
* `GetCurrentProcessId`
* `GetLastError`
* `GetProcessHeap`
* `GetSystemInfo`
* `GetSystemTimeAsFileTime`
* `GetThreadPriority`
* `GetTickCount64`
* `HeapAlloc`
* `HeapFree`
* `HeapReAlloc`
* `HeapSize`
* `QueryPerformanceCounter`
* `QueryPerformanceFrequency`
* `SetConsoleCtrlHandler`
* `SetLastError`
* `SetThreadPriority`
* `TerminateProcess`
* `TlsAlloc`
* `TlsGetValue`
* `TlsSetValue`

### Standard Windows driver APIs that mcfgthread uses

* `NtClose`
* `NtCreateSection`
* `NtDuplicateObject`
* `NtMapViewOfSection`
* `NtUnmapViewOfSection`
* `NtWaitForSingleObject`

### Undocumented functions that mcfgthread uses

* `BaseGetNamedObjectDirectory` [called by `CreateFileMappingW(...)`]
* `LdrAddRefDll` [called by `GetModuleHandleExW(GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS | GET_MODULE_HANDLE_EX_FLAG_PIN, ...)`]
* `NtDelayExecution` [called by `SleepEx()`]
* `NtProtectVirtualMemory` [called by `VirtualProtect()`]
* `NtReleaseKeyedEvent`
* `NtWaitForKeyedEvent`
* `NtYieldExecution` [called by `SwitchToThread()`]
* `RtlDllShutdownInProgress`

**Comment by brechtsanders** [comment]
I haven't tried on Windows 10 yet, though there was a point in time I was considering downgrading back to Windows 10 just because of this issue.

Any chance any of the `WaitFor` don't behave as you expect when the CPU is 100% busy, and there is some result status not handled properly?

From what I gather the blue screens were related to memory, but I haven't been able to get more detail.

I wanted to analyze a full memory dump, but that didn't work on my 64GB system.

One more minor detail: I always use RAM disk to build from source (using IMdisk) as it's a lot faster and avoids wear and tear on disks or flash media. But I tried without RAM drive and still got the same crashes.

**Comment by lhmouse** [comment]
My understanding about the GNU build system is that all processes are single-threaded, so it's unlikely that `NtWaitForKeyedEvent()` can ever be called.

But anyway, let's try it. All calls to `NtWaitForKeyedEvent()` are redirected to an inline wrapper
https://github.com/lhmouse/mcfgthread/blob/38804c0d407ad4e3a0af88bb41d22c9cd313acc2/mcfgthread/xglobals.i#L350
, which contains an assertion (but I suspect it's in active most of the time). It's likely that there are status codes other than `STATUS_WAIT_0` and `STATUS_TIMEOUT` that should be handled.

Would you please apply this patch locally and see whether any unexpected status code is returned?
[ntstatus_check.patch](https://github.com/lhmouse/mcfgthread/files/12208842/ntstatus_check.patch)

**Comment by lhmouse** [comment]
Just had someone test a CI build with [ci/build.sh](https://github.com/lhmouse/mcfgthread/blob/master/ci/build.sh) on Windows 11 Pro and there didn't seem to be any issue:

![zahD1ohs](https://github.com/lhmouse/mcfgthread/assets/5071344/83175262-ebe8-434c-9177-0dc2cecfb70e)

**Comment by starg2** [comment]
FYI, I have successfully built gcc 13.2.0 with mcf thread model (without ntstatus_check.patch) on Windows 11 without issues.

**Comment by FrankHB** [comment]
I've recently tried MSYS2 GCC 13.1 with my projects. Both MinGW64 and MinGW64 UCRT may generate wrong code (while no problems with MSYS2 MinGW32, Arch Linux x64 and MinGW64 GCC 12). Not sure relavant here, but there do have certain risks of the toolchain update.

**Comment by lhmouse** [comment]
> I've recently tried MSYS2 GCC 13.1 with my projects. Both MinGW64 and MinGW64 UCRT may generate wrong code (while no problems with MSYS2 MinGW32 10/12, MinGW64 GCC 12, Arch Linux x64 GCC 12/13.1, Debian-based GCC 7 and MSYS2 MinGW Clang64 16.0.5; BTW Clang++ 16.0.4 has ICE). Not sure relevant here, but there do have certain risks of the toolchain update.

That sounds a generic issue, not relevant to the active thread model. It is nevertheless always an OS bug if a user-mode program can effect a BSoD, but we need to figure out how to avoid it.

**Comment by FrankHB** [comment]
From 2020-12-08 to late 2022, my Surface Book 2 randomly crashed with similar GCC ICE, and more fatal errors like memory failure (even during reinstalling Windows due to corruption of copied installation image on local HDD). This seems a kernel bug finally fixed by some Windows update.

**Comment by brechtsanders** [comment]
In my case it already looks like it's stable after yesterday's firmware update. So my issue may have been a motherboard issue...
